# Generated by Django 5.2.6 on 2025-09-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articleimage",
            name="article",
        ),
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ("-published_at", "-id")},
        ),
        migrations.RenameIndex(
            model_name="article",
            new_name="articles_pub_idx",
            old_name="articles_ar_publish_c1a2fc_idx",
        ),
        migrations.RemoveField(
            model_name="article",
            name="author_name",
        ),
        migrations.RemoveField(
            model_name="article",
            name="tags",
        ),
        migrations.AlterField(
            model_name="article",
            name="blocks",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="main_image_caption",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="article",
            name="main_image_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=520),
        ),
        migrations.AlterField(
            model_name="article",
            name="source_url",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.DeleteModel(
            name="ArticleImage",
        ),
    ]
