# Generated by Django 5.2.6 on 2025-09-20 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_remove_articleimage_article_alter_article_options_and_more"),
        ("sources", "0002_source_alter_category_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="article",
            name="origin",
            field=models.CharField(
                choices=[("crawler", "Crawler"), ("user", "User")],
                default="crawler",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="source_url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_visible", "-published_at"], name="articles_vis_pub_idx"
            ),
        ),
    ]
