# Generated by Django 5.2.6 on 2025-09-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_comment_options_alter_comment_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
