# Generated by Django 5.2.6 on 2025-09-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("homepage", models.URLField(blank=True, null=True)),
                ("rss_url", models.URLField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("source_score", models.FloatField(default=1.0)),
                ("last_crawled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=160, null=True),
        ),
    ]
